### PR TITLE
Check IDN domains against the PSL correctly

### LINKED ISSUE #78: Incorrect handling of Internationalized Domain Names when checking public suffix list
Internationalized domain names are failing the public suffix list check.

For example, .政务 which translates to punycode .xn--zfr164b

Domains in the psl are utf-8 rather than punycode, fixes are to read in the psl in a utf safe way, and convert incoming domain names from punycode to unicode before checking.

My current fix brings in a dependency of Net::IDN::Encode, would appreciate thoughts on the best way to approach this. @msimerson 

https://github.com/fastmail/mail-dmarc/commit/1ba5b44d6f66f4f6eb735bbdde534f4a6b150ee3

### PR DESCRIPTION
**Pull request by marcbradshaw**
Fix PSL Lookups for IDN top level domain names.

Fixes #78

### CODE REVIEW

File: lib/Mail/DMARC/Base.pm [hunk 1]
```diff
@@ -97,13 +98,15 @@ sub any_inet_pton {
...
             or croak "unable to open $file for read: $!\n";
         # load PSL into hash for fast lookups, esp. for long running daemons
+        my @data = <$fh>;
+        close $fh;
         my %psl = map { $_ => 1 }
                   grep { $_ !~ /^[\/\s]/ } # weed out comments & whitespace
                   map { chomp($_); $_ }    # remove line endings
-                  <$fh>;
+                  @data;
         return $public_suffixes = \%psl;
```
Comment (msimerson) [inline lib/Mail/DMARC/Base.pm]: Out of curiosity, why read into @data here, vs reading line-by-line from the file handle?

**Comment by msimerson** [comment]
This looks very good to me. Well done.

File: lib/Mail/DMARC/Base.pm (hunk 1 above)
Comment (marcbradshaw) [inline lib/Mail/DMARC/Base.pm]: No reason, but it makes more sense to read line by line so let's change that.
