### PR TITLE
when message has no DKIM result, add "none"

### LINKED ISSUE #106: save_aggregate in DMARC.pm fails when provided with DKIM verifier object.
I have run into a problem when I provide the dmarc object with the DKIM verifier object in line 259 in DMARC.pm.  $self->dkim does not exist.  If I provide the dmarc object with and explicit array of dkim results however there is no problem.

...
my $dmarc = Mail::DMARC::PurePerl->new();
my $dkim = Mail::DKIM::Verifier->new();

$dmarc->source_ip('127.0.0.1');
$dmarc->envelope_to('yahoo.ca');
$dmarc->envelope_from('yahoo.ca');
$dmarc->header_from('yahoo.ca');

my $fh;	
open($fh, "<:raw", $filename)
	or return("Can't open file $filename");

$dkim->load($fh);
$dkim->CLOSE;
$dmarc->dkim($dkim);   <--- this does not work, while $dmarc->dkim(domain => 'yahoo.ca', result => 'fail'); this does.

...
my $dmarcResult = $dmarc->validate(); <--- croaks if I use dkim verifier directly.

### PR DESCRIPTION
**Pull request by msimerson**
fixes #106

### CODE REVIEW

File: lib/Mail/DMARC.pm [hunk 1]
```diff
@@ -130,6 +133,15 @@ sub _from_mail_dkim {
                 human_result => $s->result_detail,
             );
     }
+
+    if ($signatures < 1) {
+        push @{ $self->{dkim}},
+            Mail::DMARC::Report::Aggregate::Record::Auth_Results::DKIM->new(
```
Comment (marcbradshaw) [inline lib/Mail/DMARC.pm]: I don't like adding a fake domain here, it feels wrong, and could end up in reports which would be confusing. It's better if we make the is_valid method of ::DKIM allow domain to be undef when result is none, and then make sure that any dependent code does the right thing with that.

Comment (msimerson) [reply lib/Mail/DMARC.pm]: Good point about the fake domain. If there was to be a fake domain, it should definitely end with a reserved TLD such as `.invalid`. Perhaps using an empty string is better?  And then test for defined-ness?

Comment (marcbradshaw) [reply lib/Mail/DMARC.pm]: Yes, that should work better
